# Options for analysis running.
run:
  timeout: 8m
  go: "1.23"
# output configuration options
# All available settings of specific linters.
linters-settings:
  revive:
    rules:
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#argument-limit
      - name: argument-limit
        severity: warning
        disabled: false
        arguments: [5]
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#function-result-limit
      - name: function-result-limit
        severity: warning
        disabled: false
        arguments: [3]
  wrapcheck:
    ignorePackageGlobs:
      # ignore this package, as it wraps errors to add logging context
      - github.com/vbogdanov/logctx
      - github.com/labstack/echo/v4
linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - decorder
    - dogsled
    - dupl
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - err113
    - gofmt
    - goimports
    - mnd
    - goprintffuncname
    - gosec
    - grouper
    - importas
    - interfacebloat
    - ireturn
    - lll
    - maintidx
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nosprintfhostport
    - prealloc
    - predeclared
    - reassign
    - revive
    - stylecheck
    - tenv
    - testableexamples
    - testpackage
    - unconvert
    - unparam
    - usestdlibvars
    - whitespace
    - wrapcheck
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - goconst
        - dupl
        - gochecknoglobals
        - wrapcheck
